### PR TITLE
test(product): adding more tests on products

### PR DESCRIPTION
**Pull request by Oupsla**
Resolve https://github.com/Oupsla/BtrShop-cloud/issues/7

### CODE REVIEW

**Review by CharlieMcFly — APPROVED** [review]

**Comment by rouvoy** [comment]
Why some of the tests are returning a `200` on error while other errors may return `400`?

**Comment by Oupsla** [comment]
Can you comment tests that you think are wrong ? Thank you

**Comment by rouvoy** [comment]
I refer to all the tests covering incorrect parameters, some are expecting 200 error codes, others 400. What is the underlying justification for considering that an unknown parameter results in an empty list of products? If the developer makes a mistake in the parameter, she might not understand why she obtains an empty list.

**Comment by Oupsla** [comment]
Ok I understand
Yes it was to not reveal members of the model product but it is useless.
I'll change it to return a 404 when a parameter is not correct

**Comment by rouvoy** [comment]
Ok, and don't forget to make the error explicit with a human readable description, not just an error code which can be misleading when developing atop of the API.

**Pull request merged**
